version: '3.8'

services:

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: Mk3OEYBSD34fcwNTJENDLw
    networks:
      - cursed-net

  auth-db:
    image: postgres:15
    container_name: db-auth
    environment:
      POSTGRES_DB: db_auth
      POSTGRES_USER: aigerim
      POSTGRES_PASSWORD: password123
    ports:
      - "5434:5432"
    networks:
      - cursed-net

  artifact-db:
    image: postgres:15
    container_name: db-artifact
    environment:
      POSTGRES_DB: db_artifact
      POSTGRES_USER: aigerim
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    networks:
      - cursed-net

  owner-db:
    image: postgres:15
    container_name: db-owner
    environment:
      POSTGRES_DB: db_owner
      POSTGRES_USER: aigerim
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    networks:
      - cursed-net

  auth-service:
    build: ./auth.service
    container_name: auth-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/db_auth
      SPRING_DATASOURCE_USERNAME: aigerim
      SPRING_DATASOURCE_PASSWORD: password123
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_SECRET: MyVerySecretKeyForJWTSigningThatIsLongEnough32chars!
    depends_on:
      - auth-db
      - kafka
    networks:
      - cursed-net

  artifact-service:
    build: ./artifact.service
    container_name: artifact-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://artifact-db:5432/db_artifact
      SPRING_DATASOURCE_USERNAME: aigerim
      SPRING_DATASOURCE_PASSWORD: password123
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_SECRET: MyVerySecretKeyForJWTSigningThatIsLongEnough32chars!
    depends_on:
      - artifact-db
      - kafka
    networks:
      - cursed-net

  owner-service:
    build: ./owner.service
    container_name: owner-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://owner-db:5432/db_owner
      SPRING_DATASOURCE_USERNAME: aigerim
      SPRING_DATASOURCE_PASSWORD: password123
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      FEIGN_CLIENT_ARTIFACT_SERVICE_URL: http://artifact-service:8081
      JWT_SECRET: MyVerySecretKeyForJWTSigningThatIsLongEnough32chars!
    depends_on:
      - owner-db
      - artifact-service
      - kafka
    networks:
      - cursed-net

  notification-service:
    build: ./notification.service
    container_name: notification-service
    ports:
      - "8083:8083"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - cursed-net

networks:
  cursed-net:
    driver: bridge