spring:
  application:
    name: artifact.service

  datasource:
    url: jdbc:postgresql://localhost:5432/db_artifact
    username: aigerim
    password: password123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8081
