spring:
  application:
    name: owner.service
  datasource:
    url: jdbc:postgresql://localhost:5433/db_owner
    username: aigerim
    password: password123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cursed-group
      auto-offset-reset: earliest

jwt:
  secret: MyVerySecretKeyForJWTSigningThatIsLongEnough32chars!

server:
  port: 8082

feign:
  client:
    artifact-service:
      url: http://localhost:8081